version: '3'

services:
  highzer:
    image: ghcr.io/breuerfelix/uploadpy:latest
    restart: always
    build: .
    environment:
      - PORT=80
      - PASSPHRASE=uploadpy
    volumes:
      - ./data:/usr/app/data
